# Generated by Django 4.1.2 on 2022-10-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('schedule_html', models.TextField()),
                ('occupied_classrooms', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
