# Generated by Django 4.1.2 on 2022-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_class_delete_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='id',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
